version: '3.8'
services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - ipfs
    networks:
      - app-network
networks:
  app-network:
volumes:
  ipfs_staging:
  ipfs_data:
